### ISSUE TITLE
First notification is missed when app is killed

### ISSUE THREAD

**Issue by aarkalyk** [ianlin/react-native-voip-push-notification#16]
I'm encountering super weird bug. Basically, when I kill the app and send pushes, on the first push callKit is never shown, but it's shown on the following ones. I built the app in release mode, iOS version: 10.3.3. 

Has anyone encountered this issue? Anyone solved it? 

It might be related to issue #14 .

**Comment by aarkalyk** [comment]
Turns out I've been registering for voip notifications and setting `PushKit` delegate in `AppDelegate.m` file. It messed up with `RNVoipPushNotificationManager.requestPermission()`. My bad 😬

**Comment by platonish** [comment]
@aarkalyk I also had setup push notifications according to the docs for [PushNotificationIos](https://facebook.github.io/react-native/docs/pushnotificationios). I removed it, but I'm still facing the same issue. Could you please help me out? 

Here's my AppDelegate.m file:

<details><summary>AppDelegate.m</summary>
<p>



```python
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>

#import <PushKit/PushKit.h>
#import "RNVoipPushNotificationManager.h"

#import "RNSplashScreen.h"

#import "RNCallKit.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions bridgeManagerDelegate:self];
  return YES;
}


- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  RNCallKit *rncallkit = [[RNCallKit alloc] init];
  return @[rncallkit];
}

/* Add PushKit delegate method */

// Handle updated push credentials
- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(NSString *)type {
  // Register VoIP push token (a property of PKPushCredentials) with server
  [RNVoipPushNotificationManager didUpdatePushCredentials:credentials forType:(NSString *)type];
}

// Handle incoming pushes
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type {
  // Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
}

@end
```

</p>
</details>

**Comment by platonish** [comment]
@ianlin @zxcpoiu Could you please help me out here? This is causing my app to miss calls in many instances. I find this mentioned in multiple issues but I can't find a solution 😕

**Comment by aleksaToljic** [comment]
> @ianlin @zxcpoiu Could you please help me out here? This is causing my app to miss calls in many instances. I find this mentioned in multiple issues but I can't find a solution 😕

@platonish have you found the solution yet?
