### ISSUE TITLE
question

### ISSUE THREAD

**Issue by npomfret** [ianlin/react-native-voip-push-notification#2]
Thanks for this project, looking forward to giving it a ago.

I'm currently using regular push notifications but am finding them to be quite unreliable, especially the _silent_ type that interact with my app and deliver some data, hence looking at voip notifications now.  My question is, are VOIP messages different in any way from "normal" apple push notifications?

**Comment by ianlin** [comment]
Thanks. The payloads are the same while the size of the VoIP one can be bigger. VoIP push needs different token. And if I recall correctly Apple would reject the app if using VoIP push in a non-VoIP app.

**Comment by npomfret** [comment]
Thanks, I'll give it a go.
