### ISSUE TITLE
App requests permission in development but after archived to ipa it doesnt request permission any more

### ISSUE THREAD

**Issue by namnm** [ianlin/react-native-voip-push-notification#25]
Hi, I'm having the issue that my app requests permission normally in development but after archived to ipa it doesnt request permission any more. Any idea? Thanks.

**Comment by neo125874** [comment]
@namnm @ianlin hi, any solution?

**Comment by namnm** [comment]
Hi, I got it worked:
- Make sure you have configured the plist.info file correctly like the documentation.
- Make sure to have the correct app distribution certificate.
- Try to call the function getting the apns token as soon as possible, may be best is BEFORE the app rendering, store it somewhere, then get it back when you need.

**Comment by neo125874** [comment]
@namnm @ianlin thanks for the quickly response, I got this worked too.

In my situation, I used OneSignal & the voip registered at OneSignal should add the device to it after get voip token, but the OneSignal api has the test_type parameter which 1 for development & omit for archieve. 

thanks for the keyword certificate!
